["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
ERC721 = [
    "src/ERC721.cairo",
]

["protostar.test"]
disable-hint-validation = true